Updated National Rules
admin-ch/CovidCertificate-App-Verifier-Service pull request #22
Opened 2021-07-02 04:05 UTC by bachmann-ubique

2021-07-02 06:39 UTC, lmeinen approved these changes
Looks good to me!

2021-07-02 07:07 UTC, benz-ubique approved these changes

2021-07-02 07:21 UTC, benz-ubique requested changes
ist noch nicht korrekt, sehe gerade meine liste auf android war kleiner

2021-07-05 20:05 UTC, UBaggeler commented
Superseeded by #25

2021-07-05 20:05 UTC, closed without merging