Feature/eu cert logic
admin-ch/CovidCertificate-App-Verifier-Service pull request #44
Opened 2021-08-27 07:15 UTC by ubamrein

This Pull-Request marks the start of the transition to be fully compliant with "CertLogic" and the EU-Gateway format.

We introduce a function to downgrade the new format to the previously format, though, for simplicity, the file is generated once and statically stored.

For the v2 endpoint, the value-sets dynamically fetched from the gateway are injected. Further, we now allow the usage of CertLogic to evaluate to date-time expressions, to allow clients to present "validFrom" and "validTo" based on this logic.

2021-09-09 16:04 UTC, ubhaller requested changes

2021-09-09 16:04 UTC, ubhaller commented on ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/verifier/ws/controller/VerificationRulesControllerV2.java
> +        if (request.checkNotModified(verificationRulesEtag + etag)) {
springboot not modified magic only allows gzip compression if weak etags are used. check if appending two weak etags is still considered a valid weak etag (`W/\"etag1\"W/\"etag2\"`)

2021-09-09 16:04 UTC, ubhaller commented on ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/verifier/ws/controller/VerificationRulesControllerV2.java
> +                    var fieldNameIterator = entryJson.get("valueSetValues").fieldNames();
see other comment about empty iterator

2021-09-09 16:04 UTC, ubhaller commented on ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/verifier/ws/controller/VerificationRulesControllerV2.java
> +                    continue;
log exception

2021-09-10 06:01 UTC, ubamrein commented on ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/verifier/ws/controller/VerificationRulesController.java
> +    private ArrayList<Map> mapV2RulesToV1(JsonNode template) throws IOException {
yes, currently unused, but didn't want to delete the code I used to "transform" v2 (though it was manually)

2021-09-10 08:28 UTC, ubhaller approved these changes

2021-09-10 08:54 UTC, merged